# This Travis-CI file for testing the build, and eventually the
# functionality of the libfms library.
#
# This Travis-CI file was created based off the NOAA-GFDL/MOM6
# Travis-CI file.

# FMS is not a c-language project, although there are a few c-language
# sources.  However, this is the best choice.
language: c
dist: bionic
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - pkg-config gfortran netcdf-bin libnetcdf-dev libnetcdff-dev openmpi-bin libopenmpi-dev

env:
  - FCFLAGS_ADD='' CONFIGURE_OPTIONS=''
  - FCFLAGS_ADD='' CONFIGURE_OPTIONS='--without-openmp'
  - FCFLAGS_ADD='' CONFIGURE_OPTIONS='--enable-mixed-mode'
  - FCFLAGS_ADD='-fdefault-real-8 -fdefault-double-8 -fcray-pointer -ffree-line-length-none' CONFIGURE_OPTIONS='--disable-setting-flags'

# Travis sets CC to gcc, but we need to ensure it is not set, so we can use mpicc
before_install:
  - test -n "$CC" && unset CC

before_script:
  - export CC=mpicc
  - export FC=mpif90
  - export CPPFLAGS="-I/usr/include -Duse_LARGEFILE -DMAXFIELDMETHODS_=500"
  - export FCFLAGS="-Waliasing -fno-range-check ${FCFLAGS_ADD}"
  - export LDFLAGS='-L/usr/lib'
  - export LOG_DRIVER_FLAGS="--comments"

script:
  - autoreconf -i
  - ./configure ${CONFIGURE_OPTIONS}
  - make -j distcheck
