name: Build libFMS test with autotools

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        conf-flags: [--disable-openmp, --enable-mixed-mode, --disable-setting-flags, --with-mpi=no]
        input-flag:  [--with-yaml, --enable-test-input=/home/unit_tests_input]
    container:
      image: noaagfdl/hpc-me.ubuntu-minimal:gnu-input
      env:
        TEST_VERBOSE: 1
        DISTCHECK_CONFIGURE_FLAGS: "${{ matrix.conf-flags }} ${{ matrix.input-flag }}"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Prepare GNU autoconf for build
      run: autoreconf -if
    - name: Configure the build
      if: ${{ matrix.conf-flags != '--disable-setting-flags' }}
      run: ./configure ${DISTCHECK_CONFIGURE_FLAGS} || cat config.log
    - name: Configure the build with compiler flags
      if: ${{ matrix.conf-flags == '--disable-setting-flags' }}
      run: ./configure ${DISTCHECK_CONFIGURE_FLAGS} FCFLAGS="-fdefault-real-8 -fdefault-double-8 -fcray-pointer -ffree-line-length-none -I/usr/include $FCFLAGS" || cat config.log
    - name: Build the library
      run: make distcheck
      if: ${{ matrix.conf-flags != '--with-mpi=no' }}
    - name: Build the library (without test suite for serial build)
      run: make
      if: ${{ matrix.conf-flags == '--with-mpi=no' }}
