name: Pull Request CI libFMS with intel18 and intel21
  
on: [pull_request,workflow_dispatch]
jobs:
   parallelWorks:
    runs-on: [self-hosted, pw-platform]
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include:
# Turn this back on when fixed 
                - runname: FMS with intel 18
                  runscript: python3 /home/Thomas.Robinson/pw/storage/pw_api_python/PRFMSintel18StartClusters.py $GITHUB_REF
# Runs on FMS_CONTAINER_CI cluster
                - runname: FMS with intel 2021 container
                  runscript: python3 /home/Thomas.Robinson/pw/storage/pw_api_python/PRFMSintel21StartClusters.py $GITHUB_REF
    steps:
                - name: FMS make check on paralellWorks
                  env:
                          RUNNAME: ${{ matrix.runname }}
                          RUNSCRIPT: ${{ matrix.runscript }}
                  run: $RUNSCRIPT
   ShutDownCluster:
    runs-on: [self-hosted, pw-platform]
    if: always()
    needs: [parallelWorks]
    strategy:
      matrix:
        include:
                - cluster: FMS_CONTAINER_CI
                - cluster: fms_intel18_ci
    steps:
                - name: Turn off cluster
                  env:
                          CLUSTER: ${{ matrix.cluster }}
                  run: python3 /home/Thomas.Robinson/pw/storage/pw_api_python/stopClusters.py $CLUSTER
